# Generated by Django 3.1.2 on 2020-11-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='facebook_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Facebook Id'),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='token',
            field=models.TextField(verbose_name='Token'),
        ),
    ]
